platform:ios,'9.0'

target 'myhome' do
    pod 'Bugly'
#   pod 'MLeaksFinder'
    pod 'YYKit'
#   pod 'OOMDetector', '1.3'

# 三方库都要指定版本，自己的库可以不要指定版本
 
#    pod 'FSDiary'
    pod 'FSToDo'
    pod 'FSCounter'
    pod 'FSToast'
    pod 'FSCryptor'
    pod 'FSShare'
    pod 'FSGesture'
#    pod 'FSBirthday'
    pod 'FSLocation'
    pod 'FSDBMaster'
    pod 'FSTTS'

#    pod 'FSJZBus'
    pod 'FSRouter'
    pod 'FSAccount', '1.7'

    pod 'FSPassword'
#   pod 'FSJZKit'
    pod 'FSContact'

   pod 'FSJZBus', :path => '../../../Private/FSPrivateJZBus/'
   pod 'FSDiary', :path => '../../../Private/FSDiaryPrivate/'
   pod 'FSBirthday', :path => '../../../Private/FSBirthdayPrivate/'
   pod 'FSJZKit', :path => '../../../FSJZKit'


#   pod 'FSPassword', :path => '../../../Private/FSPasswordPrivate/'
#   pod 'FSAccount', :path => '../../../Private/FSAccountPrivate/'
#   pod 'FSToDo', :path => '../../../Private/FSToDoPrivate/'
#   pod 'FSContact', :path => '../../../Private/FSContactPrivate/'
#   pod 'FSRouter',:path => '../../../github/Alpha/Components/FSRouter'
#   pod 'FSTTS',:path => '../../../github/Alpha/Components/FSTTS'
#   pod 'FSLocation',:path => '../../../github/FSLocation'
#   pod 'FSCounter', :path => '../../../github/Private/FSCounterPrivate/'
#   pod 'FSShare', :path => '../../../github/FSShare'
#   pod 'FSUIKit', :path => '../../../github/FSUIKit'
#   pod 'FSBaseController', :path => '../../../FSBaseController/'
#   pod 'FSJZKit', :path => '../../../FSJZKit/'

end
