platform:ios,'9.0'

target 'myhome' do
    pod 'Bugly'
#   pod 'MLeaksFinder'
    pod 'YYKit'
#   pod 'OOMDetector', '1.3'

# 三方库都要指定版本，自己的库可以不要指定版本
 
#    pod 'FSDiary'
#    pod 'FSToDo'
    pod 'FSToast'
    pod 'FSCryptor'
#    pod 'FSShare'
    pod 'FSGesture'
#    pod 'FSBirthday'
    pod 'FSLocation'
#    pod 'FSDBMaster'
    pod 'FSTTS'

#    pod 'FSJZBus'
    pod 'FSRouter'
#    pod 'FSAccount', '1.7'

#    pod 'FSPassword'
#   pod 'FSJZKit'
#    pod 'FSContact'
#    pod 'FSCounter'

   pod 'FSDBMaster',:path => '../../../FSDBMaster/'
   pod 'FSJZBus', :path => '../../../Private/FSPrivateJZBus/'
   pod 'FSDiary', :path => '../../../Private/FSDiaryPrivate/'
   pod 'FSJZKit', :path => '../../../FSJZKit'
   pod 'FSPassword', :path => '../../../Private/FSPasswordPrivate/'
   pod 'FSToDo', :path => '../../../Private/FSToDoPrivate/'
   pod 'FSAccount', :path => '../../../Private/FSAccountPrivate/'
   pod 'FSUIKit', :path => '../../../FSUIKit'
   pod 'FSContact', :path => '../../../Private/FSContactPrivate/'
    pod 'FSCounter', :path => '../../../Private/FSCounterPrivate/'

    pod 'FSApp', :path => '../../../Alpha/Components/FSApp'

    pod 'FSBirthday', :path => '../../../Private/FSBirthdayPrivate/'
#   pod 'FSRouter',:path => '../../../github/Alpha/Components/FSRouter'
#   pod 'FSTTS',:path => '../../../github/Alpha/Components/FSTTS'
#   pod 'FSLocation',:path => '../../../github/FSLocation'
    pod 'FSViewToImage',:path => '../../../FSViewToImage'
    pod 'FSShare', :path => '../../../FSShare'
    pod 'FSBaseController', :path => '../../../FSBaseController/'
#   pod 'FSJZKit', :path => '../../../FSJZKit/'

end
